export const SERVER_URL: string = 'https://todoitnow.azurewebsites.net'
export const GRAPHQL_SERVER_URL_TEST: string = 'https://48p1r2roz4.sse.codesandbox.io'
export const APP_ID_FACEBOOK: string = 'xxx'
export const APP_ID_GOOGLE: string = 'xxx'
export const CONNECT_TOKEN: string = '/connect/token'