export type AuthorizationResponse = {
    "accessToken": "string",
    "acrValues": "string",
    "assertion": "string",
    "audiences": [
        "string"
    ],
    "claims": "string",
    "claimsLocales": "string",
    "clientAssertion": "string",
    "clientAssertionType": "string",
    "clientId": "string",
    "clientSecret": "string",
    "code": "string",
    "codeChallenge": "string",
    "codeChallengeMethod": "string",
    "codeVerifier": "string",
    "display": "string",
    "grantType": "string",
    "identityProvider": "string",
    "idTokenHint": "string",
    "loginHint": "string",
    "maxAge": 0,
    "nonce": "string",
    "password": "string",
    "postLogoutRedirectUri": "string",
    "prompt": "string",
    "redirectUri": "string",
    "refreshToken": "string",
    "request": "string",
    "requestId": "string",
    "requestUri": "string",
    "resources": [
        "string"
    ],
    "responseMode": "string",
    "responseType": "string",
    "scope": "string",
    "state": "string",
    "token": "string",
    "tokenTypeHint": "string",
    "registration": "string",
    "uiLocales": "string",
    "username": "string"
}